<?php

namespace AppBundle\Repository;

/**
 * ContactFormSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactFormSubmissionRepository extends \Doctrine\ORM\EntityRepository
{
}
