<?php

namespace AppBundle\Repository\Request;

/**
 * CancellationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CancellationRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
