<?php

namespace AppBundle\Repository\Request;

/**
 * ModificationRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModificationRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
